version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - '9001:6379'
    volumes:
      - redis-data:/data

  app:
    build: ./php
    command: 'php -S 0.0.0.0:9000'
    working_dir: /app
    ports:
      - '9000:9000'
    environment:
      REDIS_SERVER: 'redis:6379'
    volumes:
      - ./:/app

volumes:
  redis-data:
